import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import Head from 'expo-router/head';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { APP_LANGUAGE_STORAGE_KEY, isRtlLanguage, parseStoredLanguage, type AppLanguage } from '../../lib/app-language';

const COPY: Record<AppLanguage, {
  back: string;
  title: string;
  subtitle: string;
  languageNote: string;
  updated: string;
  terms: string;
}> = {
  en: {
    back: 'Back',
    title: 'Privacy Policy',
    subtitle: 'How NutriFlow handles app data in this early preview.',
    languageNote: 'This initial policy is provided in English. Localized legal text will be expanded as the product matures.',
    updated: 'Initial MVP version',
    terms: 'Terms / Disclaimer',
  },
  de: {
    back: 'Zurück',
    title: 'Datenschutzhinweise',
    subtitle: 'Wie NutriFlow App-Daten in dieser frühen Vorschau verarbeitet.',
    languageNote: 'Diese erste Fassung ist auf Englisch. Vollständig lokalisierte Rechtstexte werden mit der Produktreife ergänzt.',
    updated: 'Erste MVP-Version',
    terms: 'Nutzungsbedingungen / Disclaimer',
  },
  fa: {
    back: 'بازگشت',
    title: 'سیاست حریم خصوصی',
    subtitle: 'NutriFlow در این پیش‌نمایش اولیه چگونه داده‌های برنامه را مدیریت می‌کند.',
    languageNote: 'این نسخه اولیه به انگلیسی ارائه شده است. متن حقوقی کاملاً بومی‌سازی‌شده در نسخه‌های بعدی تکمیل می‌شود.',
    updated: 'نسخه اولیه MVP',
    terms: 'شرایط / سلب مسئولیت',
  },
};

const PRIVACY_SECTIONS = [
  {
    title: 'What health-related data NutriFlow processes',
    body:
      'NutriFlow may process wellness and health-adjacent information you enter or create in the app: symptoms, digestion notes, stool and comfort check-ins, meal descriptions, meal photos, selected wellness context, supplement logs, food history, educational meal estimates, AI-generated analysis, feedback corrections, language preference, consent state, and app settings. If you grant location permission, the app may use broad local context such as city/region for nearby-food suggestions; precise coordinates are not shown in meal results.',
  },
  {
    title: 'Guest mode local-only storage',
    body:
      'Guest mode is intended for preview and tester feedback. Guest profile, onboarding answers, language preference, food history, analysis history, supplements, and related app state are stored locally on the device/browser where possible. Guest data may be removed by clearing app/browser storage or using the in-app delete option.',
  },
  {
    title: 'Signed-in Supabase sync',
    body:
      'If you sign in, NutriFlow uses Supabase for authentication and app data sync. Profile settings, onboarding details, food logs, analysis history, supplement logs, and app-owned records may be stored in Supabase so they can sync across devices. Supabase authentication may process identifiers such as your email address.',
  },
  {
    title: 'Meal photos and image analysis',
    body:
      'When you take, upload, or choose a sample meal image, NutriFlow uses the image to generate an educational meal analysis. The image data may be sent to the configured AI provider for analysis. The app stores an image reference for history: in guest mode this may be a local device/browser URI or data URL; for signed-in users, an image reference may be stored with the meal history record in Supabase. NutriFlow does not currently provide a separate long-term photo library or dedicated image backup feature.',
  },
  {
    title: 'Photo metadata and EXIF',
    body:
      'NutriFlow does not intentionally request or display EXIF fields such as camera model or GPS metadata, and the app does not separately store EXIF fields as profile data. During this MVP, uploaded or captured image bytes may still contain embedded metadata depending on the platform, browser, or picker behavior, and NutriFlow does not yet guarantee metadata stripping before AI processing. Avoid uploading photos if embedded metadata is a concern.',
  },
  {
    title: 'Educational and wellness use only',
    body:
      'NutriFlow is designed for educational gut-wellness reflection and pattern tracking. NutriFlow is not intended for emergency use, diagnosis, treatment, cure, or prevention of disease. It is not medical advice or a replacement for a clinician. Red-flag symptoms should be handled through medical or emergency care rather than food analysis.',
  },
  {
    title: 'AI-generated analysis limitations',
    body:
      'Meal analysis may be generated by AI and can be incomplete or wrong. AI may misread photos, miss ingredients, overstate patterns, or produce text that needs correction. Scores and estimates are educational, pattern-based estimates rather than clinically validated scores.',
  },
  {
    title: 'Data deletion option',
    body:
      'Settings includes a “Delete my data” option. For guests, this clears local app data where supported. For signed-in users, NutriFlow attempts to remove app-owned profile, history, symptom, estimate, reminder, and saved meal records from Supabase. Some platform, hosting, or security logs may remain for a limited time outside the app database.',
  },
  {
    title: 'Data retention limits in this MVP',
    body:
      'NutriFlow is an early MVP and does not yet offer configurable retention schedules, data export controls, or enterprise retention guarantees. Recent-history screens may show limited windows such as the last 14 days, but signed-in records can remain in Supabase until you delete them, the project owner removes them, or retention is added later. Guest data can remain on the same device/browser until local storage is cleared or “Delete my data” is used.',
  },
  {
    title: 'Third-party services',
    body:
      'NutriFlow may use Supabase for authentication, database, and sync; Vercel for web hosting and deployment; Groq and/or Google Gemini for AI analysis depending on configuration; USDA FoodData Central for food and nutrient reference data; Expo services for app tooling and runtime workflows; and Sentry if error monitoring is enabled. These services may process the data needed to provide their part of the app, and their own terms and policies may apply.',
  },
  {
    title: 'No compliance claims',
    body:
      'This MVP does not claim HIPAA compliance, FDA clearance, MDR compliance, CE marking, clinical validation, or medical-device status.',
  },
];

export default function PrivacyPolicyScreen() {
  const [language, setLanguage] = useState<AppLanguage>('en');
  const copy = COPY[language];
  const isRtl = isRtlLanguage(language);

  useEffect(() => {
    AsyncStorage.getItem(APP_LANGUAGE_STORAGE_KEY)
      .then((storedLanguage) => setLanguage(parseStoredLanguage(storedLanguage)))
      .catch(console.warn);
  }, []);

  return (
    <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>
      <Head>
        <title>NutriFlow Privacy Policy</title>
        <meta
          name="description"
          content="Initial NutriFlow privacy policy for guest mode, Supabase sync, AI analysis, data deletion, and third-party services."
        />
      </Head>
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Pressable onPress={() => router.back()} style={[styles.backButton, isRtl && styles.rtlRow]}>
          <Ionicons name={isRtl ? 'chevron-forward' : 'chevron-back'} size={18} color="#15212D" />
          <Text style={[styles.backText, isRtl && styles.rtlText]}>{copy.back}</Text>
        </Pressable>

        <View style={styles.header}>
          <Text style={[styles.kicker, isRtl && styles.rtlText]}>NutriFlow</Text>
          <Text style={[styles.title, isRtl && styles.rtlText]}>{copy.title}</Text>
          <Text style={[styles.subtitle, isRtl && styles.rtlText]}>{copy.subtitle}</Text>
          <Text style={[styles.note, isRtl && styles.rtlText]}>{copy.languageNote}</Text>
          <Text style={[styles.updated, isRtl && styles.rtlText]}>{copy.updated}</Text>
        </View>

        {PRIVACY_SECTIONS.map((section) => (
          <View key={section.title} style={styles.section}>
            <Text style={[styles.sectionTitle, isRtl && styles.rtlText]}>{section.title}</Text>
            <Text style={[styles.sectionBody, isRtl && styles.rtlText]}>{section.body}</Text>
          </View>
        ))}

        <Pressable
          onPress={() => router.push('/terms-disclaimer' as never)}
          style={[styles.linkButton, isRtl && styles.rtlRow]}
        >
          <Ionicons name="document-text-outline" size={18} color="#276E3A" />
          <Text style={[styles.linkButtonText, isRtl && styles.rtlText]}>{copy.terms}</Text>
        </Pressable>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#F4F5F0',
    flex: 1,
  },
  content: {
    alignSelf: 'center',
    gap: 14,
    maxWidth: 860,
    padding: 20,
    paddingBottom: 44,
    width: '100%',
  },
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E4DE',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  backText: {
    color: '#15212D',
    fontSize: 14,
    fontWeight: '800',
  },
  header: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E4DE',
    borderRadius: 8,
    borderWidth: 1,
    padding: 22,
  },
  kicker: {
    color: '#4CAF50',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#15212D',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 40,
    marginTop: 8,
  },
  subtitle: {
    color: '#53616D',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
  },
  note: {
    color: '#276E3A',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 21,
    marginTop: 14,
  },
  updated: {
    color: '#7B8790',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E4DE',
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: {
    color: '#15212D',
    fontSize: 19,
    fontWeight: '900',
  },
  sectionBody: {
    color: '#53616D',
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  linkButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#E8F5EC',
    borderColor: '#BFE5CB',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  linkButtonText: {
    color: '#276E3A',
    fontSize: 15,
    fontWeight: '900',
  },
  rtlText: {
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  rtlRow: {
    flexDirection: 'row-reverse',
  },
});
